# -*- coding: utf-8 -*-
"""Workout.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pkFh0zQbV76oMfoc1wlmZMRMlc8K-avU
"""

#for custom interval circuit workouts, prints the next exercise prompt and has built in circuit timer with ding for start, click halfway, bell at end of each exercise
import time
import random
import IPython.display as display
from IPython.display import Audio

#setting up start/halfway/end sounds, note that once colab runtime gone, need to upload mp3 files again 
ding = Audio('Ding-sound-effect.mp3', autoplay = True) #start sound, will need to reload if lose runtime, https://www.freesoundslibrary.com/ding-sound-effect/
bell = Audio('bell-rings-short.mp3',autoplay = True) #end sound, https://www.freesoundslibrary.com/bell-rings-short/
click = Audio('computer-mouse-click-sound.mp3' ,autoplay = True) #halfway sound, two clicks kind of like "half" and "way" https://www.freesoundslibrary.com/computer-mouse-click-sound/

#exercises, can definitely change or add if desired
cardio = ['Jumping Jacks', 'High Knees', 'Mountain Climbers', 'Karate front kicks', 'Burpees (no pushup)']
strength = ['Pushups/Down Dog Thing','(Jump) Squats','Heel/calf Raises','Curtsy Lunges', 'Wide/Plie Squats']
core = ['Plank', 'Mermaids/Navy SEAL Side Crunch', 'Climb The Leg','Dead Bug + Out to Side','Up/Down Plank','Side Plank', 'Crunches', 'Superman']

#if want to randomize, uncomment the next three lines:

cardio = random.sample(cardio,len(cardio))
strength = random.sample(strength, len(strength))
core = random.sample(core, len(core))


#ask for active time and rest time setup
print('Welcome to your custom workout! First, two questions to set up your intervals: ')
active = int(input('How many seconds "on" per exercise?\n(ex: 50) \n'))
rest = int(input('How many seconds rest after each exercise?\n(ex: 10) \n' ))
print('Now, we will first do a main circuit, followed by a core sequence.')

#Workout!

#start w/ HIIT, active secs on, rest secs off. Alternating cardio and strength. Asks user how long to work out for
rounds = int(input('How many rounds do you want to do for the main circuit?\n (A round is 1 cardio, 1 strength and would take a total of ' + str(2*rest+2*active) + ' seconds.\n'))
for i in range(rounds): #each round is 1 cardio, 1 strength (50 secs on/10 secs off recommended)
  print('Round ' + str(i+1) + ' of ' + str(rounds))
  print(cardio[i%len(cardio)] + ': ' + str(active) +' secs')
  display.display(ding)
  time.sleep(active/2)
  print('Halfway!')
  display.display(click)
  time.sleep(active/2)
  display.display(bell)
  print('REST ' + str(rest) + ' secs\n Next: ' + strength[i%len(strength)])
  time.sleep(rest)
  display.display(ding)
  print(strength[i%len(strength)] + ': ' + str(active) + ' secs')
  time.sleep(active/2)
  print('Halfway!')
  display.display(click)
  time.sleep(active/2)
  display.display(bell)
  if i != rounds - 1:
    print('REST ' + str(rest) + ' secs\n Next: ' + cardio[(i+1)%len(cardio)])
    time.sleep(rest)
  else:
    print('Circuit completed! Great job! Now, on to core...')

#Core, user can say how long
rounds = int(input('How many rounds do you want to do the core circuit for? \n (Each round is one exercise, lasting ' + str(active+rest) + ' seconds)\n'))
for i in range(rounds):
  print('Round ' + str(i+1) + ' of ' + str(rounds))
  display.display(ding)
  print(core[i%len(core)] + ': ' + str(active) + ' secs')
  time.sleep(active/2)
  print('Halfway!')
  display.display(click)
  time.sleep(active/2)
  display.display(bell)
  if i != rounds -1:
    print('Rest ' + str(rest) +' secs\n Next: '+ core[(i+1)%len(core)])
    time.sleep(rest)
  else:
    print('All done! Nice work! Be sure to stretch it out, cool it down, and stay hydrated :)')

from IPython.display import Audio

import IPython.display as display
ding = Audio('Ding-sound-effect.mp3', autoplay = True)
Audio(url = 'https://www.freesoundslibrary.com/bell-rings-short/',autoplay = True)
display.display(ding)
#time.sleep(2)
#display.display(horse)
#Audio(url="http://www.w3schools.com/html/horse.ogg", autoplay = True)